# Generated by Django 4.2.6 on 2023-10-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
